#!/usr/bin/env python
from PIL import Image
from PIL import ImageDraw
import sys
import argparse
import json
import math

class Slices:

	def slice(self, z):
		for name,obj in self.world["world"].items():
			self.renderers[obj["type"]](obj, z)

	### Draws sphere
	def sphere(self,obj, z):
		if z<obj["center"][2]-obj["radius"] or z>obj["center"][2]+obj["radius"]:
			return
		squared_radius = obj["radius"]*obj["radius"]-(obj["center"][2]-z)*(obj["center"][2]-z)
		radius=math.sqrt(math.fabs(squared_radius))
		self.canvas.ellipse([
				(obj["center"][0]-radius) * self.world["output"],
				(obj["center"][1]-radius) * self.world["output"],
				(obj["center"][0]+radius) * self.world["output"],
				(obj["center"][1]+radius) * self.world["output"]
			]
			,outline=tuple(obj["color"]))


	### Draws cylider
	def cylinder(self,obj, z):
		if z>obj["center"][2]+obj["heigth"] or z<obj["center"][2]:
			return
		self.canvas.ellipse([
				(obj["center"][0]-obj["radius"]) * self.world["output"],
				(obj["center"][1]-obj["radius"]) * self.world["output"],
				(obj["center"][0]+obj["radius"]) * self.world["output"],
				(obj["center"][1]+obj["radius"]) * self.world["output"]
			]
			,outline=tuple(obj["color"]))

	def scale(self):
		for k,v in self.world["world"].items():
			self.world["world"][k]["center"][0] = self.world["world"][k]["center"][0]*self.world["output"]
			self.world["world"][k]["center"][1] = self.world["world"][k]["center"][1]*self.world["output"]
			self.world["world"][k]["radius"]    = self.world["world"][k]["radius"]   *self.world["output"]


	### Init
	def __init__(self, input_file="", output_file="", z=0.5):
		self.renderers = {
			"sphere":   self.sphere,
			"cylinder": self.cylinder
		}

		print("\n\nInput file %s" % input_file)
		print("Output file %s" % output_file)
		print("Heigth %f" % z)

		self.world = json.load(open(input_file))
		size = self.world["output"]
		output_image = Image.new("RGBA",(size,size))
		self.canvas = ImageDraw.Draw(output_image)

		if (z==0):
			self.canvas.rectangle([0,0,self.world['output']-1,self.world['output']-1], outline=(0,0,0))
		
		self.slice(z)

		output_image.save(output_file,"PNG")
		del self.canvas

def main(argv):
	parser=argparse.ArgumentParser(description="Create a tiger/zebra effect on the input image")
	parser.add_argument('-i', '--input',  help='the input image',  required=True)
	parser.add_argument('-o', '--output', help='the output image. Default: out.jpg', default='out.jpg')
	parser.add_argument('-z', '--z', help='the slice z coordinate. Default: 0.5', default=0.5)

	args=parser.parse_args(argv)
	Slices(input_file=args.input, output_file=args.output, z=float(args.z))

if __name__ == "__main__":
	main(sys.argv[1:])